import type { Lang } from "./lang";

const COPY = {
  en: {
    // Header
    siteTitle: "Portfolio Analytics",
    siteSubtitle: "Enter your holdings and get key risk metrics instantly.",
    // Form
    weightPlaceholder: "Weight %",
    addTicker: "+ Add ticker",
    analyze: "Analyze",
    analyzing: "Analyzing…",
    // Results
    resultsFor: "Results for:",
    lastMonths: "— last 12 months",
    correlationMatrix: "Correlation Matrix",
    // Main metrics
    annReturn: "Annualized Return",
    annReturnDesc: "Compound yearly return of the portfolio",
    annVol: "Annualized Volatility",
    annVolDesc: "Yearly standard deviation of returns",
    sharpe: "Sharpe Ratio",
    sharpeDesc: "Return per unit of risk (vs 5% risk-free rate)",
    maxDrawdown: "Max Drawdown",
    maxDrawdownDesc: "Worst peak-to-trough loss over the period",
    // Auth
    signIn: "Sign in with Google",
    signOut: "Sign out",
    // Portfolio manager
    myPortfolios: "My Portfolios",
    portfolioNamePlaceholder: "Portfolio name...",
    save: "Save",
    saving: "Saving...",
    noPortfolios: "No saved portfolios yet.",
    delete: "Delete",
    // Optimizer
    optimizerTitle: "Reduce Your Risk",
    optimizerSubtitle: "We find the allocation of your holdings that carries the least risk.",
    howItWorksLabel: "How does it work?",
    howItWorksBody:
      "Uses minimum-variance optimization — we find the combination of your assets that has the lowest possible volatility. No return forecasting involved, only how your assets move relative to each other.",
    optimizeButton: "Optimize for me",
    optimizeButtonLoading: "Optimizing…",
    optimizerSignInPrompt: "Sign in to optimize your own portfolio",
    cached: "cached",
    frontierTitle: "Risk–Return Map",
    frontierSubtitle: "2 000 random allocations of your assets. ★ is the lowest-risk one.",
    suggestedAllocation: "Suggested Allocation",
    projectedReturn: "Projected Return",
    projectedReturnDesc: "Estimated annualized return of this allocation",
    portfolioRisk: "Portfolio Risk",
    portfolioRiskDesc: "Annualized volatility — lower is better",
    riskAdjustedScore: "Risk-Adjusted Score",
    riskAdjustedScoreDesc: "Return per unit of risk (vs 5% risk-free rate)",
    // Discover promo
    discoverPromoEyebrow: "AI-powered",
    discoverPromoTitle: "Discover New Ideas",
    discoverPromoBody: "Type what you want exposure to — our AI finds the right stocks and builds a portfolio for you.",
    discoverPromoExamplesTitle: "Try these examples",
    discoverPromoExamplePrompt: "European luxury stocks",
    discoverPromoSearchTwo: "Green energy exposure",
    discoverPromoSearchThree: "Safe dividend aristocrats",
    discoverPromoStepOne: "Describe your theme",
    discoverPromoStepTwo: "AI finds matching stocks",
    discoverPromoStepThree: "Apply to your portfolio",
    discoverPromoOpen: "Open Discover",
    discoverPromoLocked: "Sign in required",
    discoverPromoExampleLabel: "Example",
    discoverPromoExamplePromptLabel: "Your request",
    discoverPromoExampleOne: "LVMH — global luxury leader with strong pricing power",
    discoverPromoExampleTwo: "Hermès — iconic brand with resilient demand",
    discoverPromoExampleThree: "Richemont — diversified luxury group",
    discoverPromoWhyLabel: "Why this works",
    discoverPromoWhyBody: "We use semantic search to find companies whose descriptions match your intent, then allocate weights based on relevance and diversification.",
    // Discover page
    discoverBack: "← Back to portfolio",
    discoverTitle: "Discover",
    discoverSubtitle: "Describe the theme or exposure you want. Our AI will find matching stocks and suggest weights.",
    discoverLockedEyebrow: "Members only",
    discoverLockedTitle: "Sign in to Discover",
    discoverLockedBody: "The Discover feature requires authentication. Sign in with Google to start exploring investment themes.",
    discoverPromptLabel: "Your investment theme",
    discoverSearchTitle: "What are you looking for?",
    discoverSearchBody: "Be specific. Instead of \"tech stocks\", try \"cloud infrastructure companies with recurring revenue\".",
    discoverPlaceholder: "e.g., European luxury goods manufacturers with strong pricing power...",
    discoverLoading: "Finding ideas...",
    discoverSearch: "Search",
    discoverHint: "Press Enter to search",
    discoverResultsLabel: "Results",
    discoverSave: "Save results",
    discoverSaving: "Saving...",
    discoverSaved: "Saved!",
    discoverSaveFailed: "Failed to save",
    discoverApply: "Apply to portfolio",
    discoverEmpty: "No results found. Try a different description.",
    discoverRetrievedSuffix: "companies retrieved ·",
    discoverSelectedSuffix: "selected",
    discoverUnknownError: "Something went wrong",
    discoverThinking: "AI is thinking",
    discoverThinkingStep1: "AI is understanding your query",
    discoverThinkingStep2: "AI is searching through companies",
    discoverThinkingStep3: "AI is building your portfolio",
    discoverHideContext: "Hide details",
    discoverViewContext: "View details",
    discoverSector: "Sector",
    discoverIndustry: "Industry",
    discoverCountry: "Country",
    discoverExchange: "Exchange",
    discoverSimilarity: "Similarity score",
  },
  fr: {
    // Header
    siteTitle: "Analyse de portefeuille",
    siteSubtitle: "Entrez vos positions et obtenez les indicateurs de risque clés instantanément.",
    // Form
    weightPlaceholder: "Poids %",
    addTicker: "+ Ajouter un actif",
    analyze: "Analyser",
    analyzing: "Analyse…",
    // Results
    resultsFor: "Résultats pour :",
    lastMonths: "— 12 derniers mois",
    correlationMatrix: "Matrice de corrélation",
    // Main metrics
    annReturn: "Rendement annualisé",
    annReturnDesc: "Rendement annuel composé du portefeuille",
    annVol: "Volatilité annualisée",
    annVolDesc: "Écart-type annuel des rendements",
    sharpe: "Ratio de Sharpe",
    sharpeDesc: "Rendement par unité de risque (vs taux sans risque de 5 %)",
    maxDrawdown: "Drawdown maximum",
    maxDrawdownDesc: "Pire perte pic-à-creux sur la période",
    // Auth
    signIn: "Se connecter avec Google",
    signOut: "Se déconnecter",
    // Portfolio manager
    myPortfolios: "Mes portefeuilles",
    portfolioNamePlaceholder: "Nom du portefeuille...",
    save: "Enregistrer",
    saving: "Enregistrement...",
    noPortfolios: "Aucun portefeuille sauvegardé.",
    delete: "Supprimer",
    // Optimizer
    optimizerTitle: "Réduire votre risque",
    optimizerSubtitle: "On trouve la répartition de vos actifs qui porte le moins de risque.",
    howItWorksLabel: "Comment ça marche ?",
    howItWorksBody:
      "Utilise l'optimisation de variance minimale — on trouve la combinaison de vos actifs avec la volatilité la plus faible possible. Aucune prévision de rendement : seule la façon dont vos actifs évoluent les uns par rapport aux autres compte.",
    optimizeButton: "Optimiser pour moi",
    optimizeButtonLoading: "Optimisation…",
    optimizerSignInPrompt: "Connectez-vous pour optimiser votre portefeuille",
    cached: "mis en cache",
    frontierTitle: "Carte risque–rendement",
    frontierSubtitle: "2 000 répartitions aléatoires de vos actifs. ★ est celle avec le moins de risque.",
    suggestedAllocation: "Répartition suggérée",
    projectedReturn: "Rendement estimé",
    projectedReturnDesc: "Rendement annualisé estimé de cette répartition",
    portfolioRisk: "Risque du portefeuille",
    portfolioRiskDesc: "Volatilité annualisée — plus c'est bas, mieux c'est",
    riskAdjustedScore: "Score ajusté au risque",
    riskAdjustedScoreDesc: "Rendement par unité de risque (vs taux sans risque de 5 %)",
    // Discover promo
    discoverPromoEyebrow: "Propulsé par l'IA",
    discoverPromoTitle: "Découvrir de nouvelles idées",
    discoverPromoBody: "Décrivez l'exposition souhaitée — notre IA trouve les bonnes actions et construit un portefeuille pour vous.",
    discoverPromoExamplesTitle: "Essayez ces exemples",
    discoverPromoExamplePrompt: "Actions de luxe européennes",
    discoverPromoSearchTwo: "Exposition aux énergies vertes",
    discoverPromoSearchThree: "Dividend aristocrats sûrs",
    discoverPromoStepOne: "Décrivez votre thème",
    discoverPromoStepTwo: "L'IA trouve les actions",
    discoverPromoStepThree: "Appliquez à votre portefeuille",
    discoverPromoOpen: "Ouvrir Découvrir",
    discoverPromoLocked: "Connexion requise",
    discoverPromoExampleLabel: "Exemple",
    discoverPromoExamplePromptLabel: "Votre demande",
    discoverPromoExampleOne: "LVMH — leader mondial du luxe avec un pouvoir de prix fort",
    discoverPromoExampleTwo: "Hermès — marque iconique avec une demande résiliente",
    discoverPromoExampleThree: "Richemont — groupe de luxe diversifié",
    discoverPromoWhyLabel: "Pourquoi ça marche",
    discoverPromoWhyBody: "Nous utilisons la recherche sémantique pour trouver des entreprises dont les descriptions correspondent à votre intention, puis allouons les poids basés sur la pertinence et la diversification.",
    // Discover page
    discoverBack: "← Retour au portefeuille",
    discoverTitle: "Découvrir",
    discoverSubtitle: "Décrivez le thème ou l'exposition souhaitée. Notre IA trouvera les actions correspondantes et suggérera les pondérations.",
    discoverLockedEyebrow: "Membres uniquement",
    discoverLockedTitle: "Connectez-vous pour Découvrir",
    discoverLockedBody: "La fonctionnalité Découvrir nécessite une authentification. Connectez-vous avec Google pour commencer à explorer les thèmes d'investissement.",
    discoverPromptLabel: "Votre thème d'investissement",
    discoverSearchTitle: "Que cherchez-vous ?",
    discoverSearchBody: "Soyez spécifique. Au lieu de \"actions tech\", essayez \"entreprises d'infrastructure cloud avec revenus récurrents\".",
    discoverPlaceholder: "ex: Fabricants européens de biens de luxe avec fort pouvoir de prix...",
    discoverLoading: "Recherche d'idées...",
    discoverSearch: "Rechercher",
    discoverHint: "Appuyez sur Entrée pour rechercher",
    discoverResultsLabel: "Résultats",
    discoverSave: "Enregistrer",
    discoverSaving: "Enregistrement...",
    discoverSaved: "Enregistré !",
    discoverSaveFailed: "Échec de l'enregistrement",
    discoverApply: "Appliquer au portefeuille",
    discoverEmpty: "Aucun résultat trouvé. Essayez une autre description.",
    discoverRetrievedSuffix: "entreprises trouvées ·",
    discoverSelectedSuffix: "sélectionnées",
    discoverUnknownError: "Une erreur s'est produite",
    discoverThinking: "L'IA réfléchit",
    discoverThinkingStep1: "L'IA analyse votre requête",
    discoverThinkingStep2: "L'IA recherche des entreprises",
    discoverThinkingStep3: "L'IA construit votre portefeuille",
    discoverHideContext: "Masquer les détails",
    discoverViewContext: "Voir les détails",
    discoverSector: "Secteur",
    discoverIndustry: "Industrie",
    discoverCountry: "Pays",
    discoverExchange: "Bourse",
    discoverSimilarity: "Score de similarité",
  },
} as const;

export type Copy = Record<string, string>;

export function t(lang: Lang): Copy {
  return COPY[lang];
}
